### ISSUE TITLE
NPM Package Not Found

### ISSUE THREAD

**Issue by corepay** [wuori/vue-credit-card-validation#1]
Hello, wanted to test this out but ran into problem.

![image](https://user-images.githubusercontent.com/48992923/58369391-cc23ca00-7ec7-11e9-80ea-7ebae0fa7063.png)

**Comment by wuori** [comment]
@corepay Sorry about that... I forgot to update the package name (`vue-credit-card-validation`) in the README. 

Fixed this, you can now see the correct name in the Readme. ([Commit](https://github.com/wuori/vue-credit-card-validation/commit/226768e7d5d0d0859b803336fa98d420970ac9f0#diff-04c6e90faac2675aa89e2176d2eec7d8)]
