### ISSUE TITLE
Card Expiration V-Model issue

### ISSUE THREAD

**Issue by audetcameron** [wuori/vue-credit-card-validation#11]
The card expiration field adds an extra digit to the v-model if you punched one in.
If you type 01 2021 then hit number 5, it removes the last digit from the input but is still bound to the data. You can see on the validate card details return
![image](https://user-images.githubusercontent.com/6738453/74159752-488f4200-4bea-11ea-8165-d37dbdc6af23.png)

**Comment by wuori** [comment]
@audetcameron Thanks for the catch! Will try to address this soon, but feel free to make a PR if you want.

**Comment by wuori** [comment]
@audetcameron There was a lot going on with this, so to be safe I added functionality to add the `maxlength` attribute to whatever fields the `$formatCardExpiry` directive is attached to. Seems to take care of this issue. 

This has been added and the NPM package has been updated to `0.1.8`.

Let me know if this is still an issue for you. Closing now!

**Comment by audetcameron** [comment]
> @audetcameron There was a lot going on with this, so to be safe I added functionality to add the `maxlength` attribute to whatever fields the `$formatCardExpiry` directive is attached to. Seems to take care of this issue.
> 
> This has been added and the NPM package has been updated to `0.1.8`.
> 
> Let me know if this is still an issue for you. Closing now!

Thanks for your time, I'm back on that project next week and I'll keep you posted.
