### ISSUE TITLE
[QUESTION] How to get the card brand value?

### ISSUE THREAD

**Issue by pserracomas** [wuori/vue-credit-card-validation#12]
Hello there!

First of all, I want to thank you guys for the excellent job done with the vue-credit-card-validation plugin.

I've been checking your docs and the example provided, but I haven't been able to figure out how you do it to get the card brand value. You just declare it on the data{} section and that's all.

Is there any method, like for validation pourpuses: this.$cardFormat.validateCardNumber(), where we can get the card brand from?

Many thanks!

**Comment by pserracomas** [comment]
Great! thanks @cody-baker, it worked for me too. I was just wondering if there were alternatives to get that value.

**Comment by cody-baker** [comment]
@pserracomas 👍 The only other way I know of is card brand gets added to the input as a data value (`data-card-brand`) so technically you could get it that way if you put a `$ref` on the input but it's a lot cleaner to just add `cardBrand` in your data
