### ISSUE TITLE
Error in directive cardformat bind hook: "TypeError: el is null"

### ISSUE THREAD

**Issue by developernaren** [wuori/vue-credit-card-validation#2]
Here is the code to reproduce the error

https://codesandbox.io/s/vue-template-u6er3

**Comment by wuori** [comment]
Sorry about that, I will try to fix soon! I have to upgrade some NPM packages as Github won't let me push until vulnerabilities are updated... which occurs like once a month due to the black hole that is NPM dependencies.

**Comment by dnnsldr** [comment]
Any word on an update?

**Comment by wuori** [comment]
Did you put `import VueCardFormat from "vue-credit-card-validation";` and `Vue.use(VueCardFormat);` in your main.js? I'll keep looking at this.

**Comment by Faizanq** [comment]
Any Updates?

**Comment by dmsps** [comment]
Sadly, not working cause 'el is null'

**Comment by alihyder047** [comment]
Looking for update

**Comment by wuori** [comment]
My apologies, the emails for this issue were going to my junk folder. I will look into this tonight.

**Comment by stefanheimann** [comment]
should be fixed with #7

**Comment by gpassarelli** [comment]
I believe you fixed it, but did not release it. I just download the package and still comes with the 0.15 files, even saying it's on tag 0.16

**Comment by gpassarelli** [comment]
@stefanheimann  or @wuori  can you please have a look at this? 
On a fresh install is still downloading the old version of it.

**Comment by stefanheimann** [comment]
@gpassarelli I'm sorry, I don't have the rights to publish to npm, @wuori has to take care about it or grant me rights to do it.

In the meantime you can install the package like this:

`yarn add https://github.com/wuori/vue-credit-card-validation/tarball/master`

or

`npm install https://github.com/wuori/vue-credit-card-validation/tarball/master`

**Comment by gpassarelli** [comment]
Thansk @stefanheimann it worked.

**Comment by wuori** [comment]
@gpassarelli I've updated the NPM package: https://www.npmjs.com/package/vue-credit-card-validation

@stefanheimann Again thanks for all your help!
