### ISSUE TITLE
Input Card Number is not deleting properly

### ISSUE THREAD

**Issue by claytongf** [wuori/vue-credit-card-validation#20]
This issue also can be checked in the example page
https://wuori.github.io/vue-credit-card-validation/example/
When I fill the card number input, sometimes the first two number cannot be deleted until I refresh the page. This may happen when the filter is applied. I realized that this issue occurs when the card number is less than 16 characters.

**Comment by wuori** [comment]
Will try to take a look this week but pretty slammed with work. In the meantime, feel free to open a PR. Thanks!

**Comment by wuori** [comment]
@claytongf Sorry, I've been busy with other projects. I'll try to get to this next week.

**Comment by wuori** [comment]
@claytongf can you please provide some detailed steps to replicate? Thanks!

**Comment by wuori** [comment]
@claytongf This issue if about to turn 1 year old 🎉. I haven't been able to recreate it and will be closing it. If you are still experiencing it, please create a new issue with more details on how to recreate it. Thank you!
