### ISSUE TITLE
Card brand not regocnized when you paste card number

### ISSUE THREAD

**Issue by gpassarelli** [wuori/vue-credit-card-validation#21]
This issue also can be checked on the example page
https://wuori.github.io/vue-credit-card-validation/example/

If you try to paste the card number to the card number input, the card brand won't recognize the input.

If you paste the same number you have on your example, with the formated mask: `5555 5555 5555 4444` or without formation `5555555555554444`  the card brand input will keep showing `(awating input...)`

**Comment by wuori** [comment]
@gpassarelli Thank you for explaining the issue so clearly! Looks like an issue on the paste event, not a validation issue (if you paste, blur then re-focus it works). I'll look into it when I get some time, but in the mean time please feel free to create a PR if you want to fix it before then!

**Comment by wuori** [comment]
@gpassarelli As this is not an issue with the validator, per se, but rather an implementation of the demo code, I've decided not to update the code as it may cause confusion for some other users. 

The fix to capture the card brand on paste is just to debounce whatever watcher or model you have set to listen to the credit card number input. 

To replicate a successful copy read in the demo provided in this repo, you could add a simple timeout to the listener for `cardNumber` to read like below:

```
// handle auto-focus to next field
        cardNumber: function(val){
          setTimeout(() => {
            if(this.$cardFormat.validateCardNumber(val)){
              this.$refs.cardExpInput.focus();
            }
          }, 200);
        },
```

<img width="648" alt="Screen Shot 2020-10-25 at 9 01 11 PM" src="https://user-images.githubusercontent.com/96183/97124227-a080c100-1705-11eb-9507-5c3b16dd10ed.png">
