### ISSUE TITLE
Excess card number value still retains.

### ISSUE THREAD

**Issue by by-tim** [wuori/vue-credit-card-validation#22]
**Issue description**
It seems that the computed value of the card number will retain the last excess inputted digit, although on the input it's trimmed (not visible).

**Steps to reproduce the issue**

1. On the demo page, https://wuori.github.io/vue-credit-card-validation/example/, input any valid card number (e.g. `4242 4242 4242 4242`).
2. Re-enter the input and add a digit (e.g. `4242 4242 4242 42421`).

What's the expected result?
Computed value should be `4242 4242 4242 4242`

What's the actual result?
Computed value is `4242 4242 4242 42421`

**Comment by wuori** [comment]
Thanks, @by-tim I'll try to get to this. In the meantime, feel free to submit a PR if you have a fix!

**Comment by wuori** [comment]
Poked around a bit but not enough time to fix it. It seems that even in this use case once the field is blurred it'll take off the additional number. I'll keep this issue open and respond when it's resolved.

**Comment by claytongf** [comment]
Any update about this issue?

**Comment by VeselAbaya** [comment]
Hi! I am a new user of your library and I also noticed that bug.
Lib is awesome, so don't forget about it pls! :)

**Comment by wuori** [comment]
@VeselAbaya @claytongf I'll try to get to this within the next few days if not tonight. If you've any ideas please feel free to make a PR. Thanks!

**Comment by wuori** [comment]
@claytongf @VeselAbaya @by-tim @stefanheimann This issue has been fixed and a new version `0.1.11` is now available for you to upgrade to. I will also be releasing a `1.0.0` as a divergent version that will support Vue 3. 

Thanks for all your input!
