### ISSUE TITLE
CardFormatter adds 0 after every single input

### ISSUE THREAD

**Issue by lsya24** [wuori/vue-credit-card-validation#29]
**Issue description**

Adding any number to the inputs automatically adds 0 to the current model... which makes this unusable.

**Additional information**
environment: Nuxt.js

What was written: 5432

RESULT:
![image](https://user-images.githubusercontent.com/88881769/129334914-a7a00667-faa5-4cc4-8f34-2f890e46031c.png)

**Comment by wuori** [comment]
@lsya24 Could you provide some more details? I haven't used this in Nuxt yet and can't recreate it at the moment. Include the code for the page you're using it on, that may help me. Thank you!
