### ISSUE TITLE
"vue-credit-card-validation.esm.js" isn't included in package.json "files"

### ISSUE THREAD

**Issue by midnight-industry** [wuori/vue-credit-card-validation#33]
The other files from the "dist" folder are included, but the esm module is missing (despite the fact that "module" in package.json points to it.

This results in errors when using vite (rollup) to build after npm install.

**Comment by wuori** [comment]
Thanks!

**Comment by wuori** [comment]
@midnight-industry I bumped the NPM version and it's been published. Thanks again for your contribution :)
