### ISSUE TITLE
CardFormatter validate not right when input 11111111111111

### ISSUE THREAD

**Issue by tam1004** [wuori/vue-credit-card-validation#35]
Input: 1111111111111111
Actual Result: 1111111111111111
Expected Result: 1111 1111 1111 1111
![image](https://user-images.githubusercontent.com/94376173/153788776-4023ddf8-e012-4077-b832-7a4115d0bd96.png)

**Comment by wuori** [comment]
Yeah it doesn't do anything with non-valid numbers it seems, I'll try to look at this this week, but feel free to submit a PR in the meantime

**Comment by wuori** [comment]
@tam1004 Adding a work-around for non-valid credit card numbers is a little cumbersome for this plugin as it's meant only for credit card numbers that pass the [Luhn check](https://www.dcode.fr/luhn-algorithm).

If you want to format any set of numbers in groups of 4, etc., then you can just write your own listener and look at some of the code in `formatCardNumber()` in `src/utils.js` to achieve similar formatting. 

If you feel there's a real case to add this, then by all means please submit a PR and we'll discuss! Thank you!
