### ISSUE TITLE
Dependency Free?

### ISSUE THREAD

**Issue by jmichaelterenin** [wuori/vue-credit-card-validation#45]
To anyone reading this:
I'm confused as to why the author has labeled this "dependency-free" when the example includes declarations for:
- bootstrap
- popper
- jquery
- font-awesome

Am I missing something here??

**Comment by jmichaelterenin** [comment]
Sorry, having a rough day. Of course it's dependency-free, that's the "additionals" the author has utilized in the example. 
My bad ...

**Comment by wuori** [comment]
No worries! I was confused to as I haven't worked on this in a while.
