### ISSUE TITLE
validation for multi credit card

### ISSUE THREAD

**Issue by RoshaniSTPL** [wuori/vue-credit-card-validation#47]
Hello,

I am using this package to validate the credit card numbers for a single number so, it is working fine. but when I use it for multi-card it's not working properly. also, I am trying in for loop but didn't work. can you please share your valuable input here?

Thanks in advance!!!

**Comment by wuori** [comment]
@RoshaniSTPL Can you please describe how you're trying to do multiple cards? Are you just pasting multiple numbers at once? The plugin is not currently setup to handle that I'm afraid.
